# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmijDdzh07HrXhKrEzIp2QMVskg5dE7p

## Question 6: Implement a basic Langchain pipeline using OpenAI’s LLM to answer questions based on a user input prompt.

### I tried OpenAI's API free trial key  but it keep throughing error.
### That is why I am using Groq API key.
"""

!pip install -q langchain langchain-groq -q

from google.colab import userdata

my_api_key = userdata.get('Groq_api')

from langchain_groq import ChatGroq

llm = ChatGroq(
    model='llama-3.3-70b-versatile',
    temperature=0.2,
    api_key=my_api_key
)

question = input("Ask a question: ")
answer = llm.invoke(question)
print("\nAnswer:", answer.content)

"""## Question 7: Integrate Langchain with a third-party API (e.g., weather, news) and show how responses can be generated via LLMs.

"""

# Integrating an API key for weather forecasting

import requests
from langchain_core.tools import tool

@tool
def get_weather(city: str) -> str:
    """Get the current weather for a given city name."""
    # Step A: convert city name to lat/long (free, no key needed)
    geo_url = "https://geocoding-api.open-meteo.com/v1/search"
    geo_resp = requests.get(geo_url, params={"name": city, "count": 1}).json()

    if "results" not in geo_resp or len(geo_resp["results"]) == 0:
        return f"Could not find location data for '{city}'."

    location = geo_resp["results"][0]
    lat, lon = location["latitude"], location["longitude"]
    resolved_name = location["name"]
    country = location.get("country", "")

    # Step B: fetch current weather for those coordinates
    weather_url = "https://api.open-meteo.com/v1/forecast"
    weather_resp = requests.get(weather_url, params={
        "latitude": lat,
        "longitude": lon,
        "current_weather": True
    }).json()

    current = weather_resp.get("current_weather", {})
    if not current:
        return f"Weather data unavailable for {resolved_name}."

    temp = current.get("temperature")
    windspeed = current.get("windspeed")

    return (f"Current weather in {resolved_name}, {country}: "
            f"{temp}°C, wind speed {windspeed} km/h.")

!pip install -q langchain langchain-groq requests
!pip install -U langchain langchain-core langchain-community -q

llm_with_tools = llm.bind_tools([get_weather])

from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages

class State(TypedDict):
    messages: Annotated[list, add_messages]

def assistant_node(state: State):
    # Get the conversation history
    current_messages = state["messages"]

    # Ask the LLM what to do
    response = llm_with_tools.invoke(current_messages)
    # Return the response so it gets added to the 'messages' list
    return {"messages": [response]}

tools = [get_weather]

from langgraph.prebuilt import ToolNode

tool_node = ToolNode(tools)

from typing import Literal
from langgraph.graph import END
def should_continue(state: State) -> Literal["tools", END]:
    messages = state["messages"]
    last_message = messages[-1]

    if last_message.tool_calls:
        return "tools"

    else:
        return END

from langgraph.graph import StateGraph, START

# Create a blank graph
builder = StateGraph(State)

from langgraph.graph import StateGraph, START

builder = StateGraph(State)

builder.add_node("assistant", assistant_node)
builder.add_node("tools", tool_node)          # ToolNode handles ALL tools

builder.add_edge(START, "assistant")
builder.add_conditional_edges("assistant", should_continue)
builder.add_edge("tools", "assistant")

graph = builder.compile()

# 1. Define the user's complex request
user_query = "Current weather of varanasi?"

# 2. Run the Graph
initial_state = {"messages": [("user", user_query)]}

print(f"User: {user_query}\n")

# 3. Print the final result
final_response = graph.invoke(initial_state)
print("\n🤖 Final Answer:")
print(final_response["messages"][-1].content)

"""## Question 8: Create a LamaIndex implementation that indexes a local text file and retrieves answers from it.

"""

!pip uninstall -y groq
!pip install -q groq==0.31.1

!pip install -q \
llama-index \
llama-index-llms-groq \
langchain-huggingface \
sentence-transformers

text_content = """
LangChain is a framework for developing applications powered by large language models.
It provides tools for chaining together prompts, LLMs, and external data sources.

LlamaIndex is a data framework for connecting custom data sources to large language models.
It specializes in indexing documents and retrieving relevant information for question answering.

Both frameworks are commonly used to build RAG (Retrieval Augmented Generation) applications.
"""

with open("sample.txt", "w") as f:
    f.write(text_content)

from llama_index.core import SimpleDirectoryReader

documents = SimpleDirectoryReader(input_files=["sample.txt"]).load_data()

from llama_index.llms.groq import Groq
from llama_index.core import Settings

llm = Groq(
    model="llama-3.3-70b-versatile",
    api_key=my_api_key
)

Settings.llm = llm

!pip install -q llama-index-embeddings-huggingface

from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings

embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

Settings.embed_model = embed_model

from llama_index.core import VectorStoreIndex

index = VectorStoreIndex.from_documents(documents)

query_engine = index.as_query_engine()

response = query_engine.query(
    "What is Llama Index?"
)

print(response)

"""## Question 9: Demonstrate combining Langchain with LamaIndex to create a simple document-based Q&A chatbot.

"""

!pip install -q \
llama-index \
llama-index-llms-groq \
llama-index-embeddings-huggingface \
langchain

from llama_index.core import Settings
from llama_index.llms.groq import Groq
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

Settings.llm = Groq(
    model="llama-3.3-70b-versatile",
    api_key=my_api_key
)

Settings.embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from llama_index.core import SimpleDirectoryReader, VectorStoreIndex

documents = SimpleDirectoryReader(
    input_files=["sample.txt"]
).load_data()

index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()

# Creating prompt using LangChain

from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template="""
Answer the question using the provided context.

Context:
{context}

Question:
{question}

Answer:
"""
)

# Building Q & A Chatbot

def chatbot(question):

    # Retrieve relevant information from document
    retrieved = query_engine.query(question)

    context = str(retrieved)

    final_prompt = prompt.format(
        context=context,
        question=question
    )

    response = Settings.llm.complete(final_prompt)

    return response.text

# Asking Question

while True:
    q = input("You: ")

    if q.lower() == "exit":
        break

    answer = chatbot(q)

    print("Bot:", answer)